[package]
name = "secret-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "secret-manager"

[lib]
name = "secret_manager"
path = "src/lib.rs"

[[bin]]
name = "secret-manager"
path = "src/main.rs"

[dependencies]
control-protocol = { path = "../control-protocol" }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json = "1"
postcard.workspace = true
zeroize.workspace = true
libc.workspace = true
toml = "0.8"
humantime-serde = "1"
argon2 = "0.5"
chacha20poly1305 = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
sha2 = "0.10"
hkdf = "0.12"
aes = "0.8"
cbc = { version = "0.1", features = ["alloc", "block-padding"] }
num-bigint = "0.4"
num-traits = "0.2"
uuid = { version = "1", features = ["v4"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "process", "sync", "time", "fs", "signal"] }
futures-util = "0.3"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
rpassword = "7"
regex = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
subtle = "2"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
